# Generated by Django 5.0.4 on 2026-04-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_userprofile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='products',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
